version: '3'

services:
  db: 
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=commerce_sql_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pazzo1991

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/pazzo/Desktop/Python/Web Programming/Django/Commerce-Docker/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=commerce_sql_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pazzo1991
    depends_on:
      - db