# Generated by Django 4.0.2 on 2022-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0003_alter_bid_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
