# Generated by Django 4.0.2 on 2022-03-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0011_remove_bid_listing_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
