# Generated by Django 4.0.2 on 2022-03-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0012_listing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='status',
            new_name='is_active',
        ),
    ]
