name: Testing
on: 
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  

jobs:
  Test_Commerce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Auction Unit Tests
      run: |
        pip3 install --user -r requirements.txt
        python3 manage.py test